### ISSUE TITLE
Admin - View list & manage customers

### ISSUE THREAD

**Issue by radeonxray** [Bearukun/Polygon#15]
As an admin 
I want to be able to view a list of/manage customers
So that I can add/remove/approve customers on the site

**Comment by DjKirkovic** [comment]
Admin can now login as any user:
https://github.com/Bearukun/Polygon/commit/cedd4ae236ffa3aeab03c698599d3701089a388b

**Comment by DjKirkovic** [comment]
Admin can delete users:
https://github.com/Bearukun/Polygon/commit/a7b342891ba74c545812bb7eb7871c5b4eb0a981
