### ISSUE TITLE
Admin: List and manage technicians

### ISSUE THREAD

**Issue by bjoffk** [Bearukun/Polygon#17]
As an admin
I want to be able to see and manage a list of technicians.
So that I can manage staff resources on the site.

**Comment by DjKirkovic** [comment]
Admin can edit user profiles for anyone:
https://github.com/Bearukun/Polygon/commit/0c3ab89a868b29ce89a06cb8ac525f95e48b73af

Admin can delete users:
https://github.com/Bearukun/Polygon/commit/a7b342891ba74c545812bb7eb7871c5b4eb0a981
