### ISSUE TITLE
Task: Modify current tables

### ISSUE THREAD

**Issue by DjKirkovic** [Bearukun/Polygon#24]
for user.jsp (buildings) and admin.jsp (Buildings+Users)

**Comment by radeonxray** [comment]
First stab at expanding the adminUser table https://github.com/Bearukun/Polygon/commit/a32ab589215898df58dbfa23b105921ad7a7c5ad

Fixed small error in the order of the data shown in the adminUser table
https://github.com/Bearukun/Polygon/commit/6585b89889ded9cedb40a5def5738c9125dd11e8

Updated the usersBuilding table with the expanded data and information
https://github.com/Bearukun/Polygon/commit/61b44ee9513f9d4187187be80988f3d94eac983e

Updated the adminBuilding table with the expanded data and information
https://github.com/Bearukun/Polygon/commit/37c2cbd5e53872d647ecd5cac863903d6569b52d

**Comment by radeonxray** [comment]
Update Users table for their data and information regarding all of their buildings: Done
Update admin tables for the overview of all users and all buildings: Done

#Closed
