### ISSUE TITLE
Task: Modify 'Customer details'

### ISSUE THREAD

**Issue by DjKirkovic** [Bearukun/Polygon#27]

**Comment by radeonxray** [comment]
Basic work on the editProfil being initiated: https://github.com/Bearukun/Polygon/commit/50c8575b38aef54f98585112fb5bbf83ad89b364

Continued work on editProfile. Textfields now recieves and are populated
with data, although it is currently all 'null'/0. : https://github.com/Bearukun/Polygon/commit/50c8575b38aef54f98585112fb5bbf83ad89b364

Added editProfile method to DBFacadeInterface and DBFacade.java : https://github.com/Bearukun/Polygon/commit/3974f6c119850e73d261e276a62e701dcd26b957

Added EditUser to UserControllerInterface and UserController.java
Added "editUser"-case to the Front.java
*Earlier commits mentions "editProfile", this was a spelling error. :
https://github.com/Bearukun/Polygon/commit/65ce35be17551af0e5da3acb801300fba8cc0fe4

Continued development of the editProfile.jsp - getUser(email): 
https://github.com/Bearukun/Polygon/commit/b30c2d10cff2747d8090a3427cd55c1622a3b853

editProfile.jsp (finally) displays the users current information in the
fields. : https://github.com/Bearukun/Polygon/commit/2468299f6388fa4fd1a57a8bb62a06cec90b38e6

While the correct data is being displayed in editProfile, the data aint
being funneled down into the "editProfile"-case in the "Front.java": 
https://github.com/Bearukun/Polygon/commit/fa0f3050200214c9ba0fa9844634cd5b04443cef

Still some problems with the editProfile.jsp
All data except the userID is being correctly gathered.
Manually forcing a editUser is also currently broken.: 
https://github.com/Bearukun/Polygon/commit/b72c0d7f38b94a09f9f2ced590d0c3c6dba3f002

Manually forcing a editUser now works... Uses a hard-coded user_id,
needs to be changed. Also, the logged in users info needs to update
when the user info is updated.:
https://github.com/Bearukun/Polygon/commit/8c61f80206e23f3d91cc5443d831bb7f327bb30e

Minor code/visual clean up.
Code is now able to automatically detect the user ID, which means that
the user now is able to change their all of their information.
A lot of visual and code clean up is needed.
While the user can update their info, the users page is not currently
updated with the new information.: 
https://github.com/Bearukun/Polygon/commit/a5d0fab917909cd1d70596424214f5e876004470

Code is now able to automatically detect the user ID, which means that
the user now is able to change their all of their information.
While the user can update their info, the users page is not currently
updated with the new information.:
https://github.com/Bearukun/Polygon/commit/2965d445ef23358cc80596c6c7ba49451a1f7085

Edited user information is now being displayed in the fields in the
editProfile.jsp and displayed username in the top left, immediatly after
the user have updated/saved.
Cleaned up Front.java: Commented code and outcommented SOUTS.:
https://github.com/Bearukun/Polygon/commit/708120158688330171d0956e685f8031c5357caf
