### ISSUE TITLE
Task: fix adminusers.jsp & create user password verification

### ISSUE THREAD

**Issue by DjKirkovic** [Bearukun/Polygon#44]

**Comment by radeonxray** [comment]
Admin can create and assign a new user to one of the three types of user (Customer, Admin or Technician)
https://github.com/Bearukun/Polygon/commit/8b9a25a7f96a67cfdf00650a7921b4a3f25e07cf

Fixed issue with the userlist not updating after the admin has manually created a new user
https://github.com/Bearukun/Polygon/commit/f7495cebb0f9e60c1b0a784832c20a2066c409d7

Added Javascript to tell the user, if the password matches when they create a new user (customer)
https://github.com/Bearukun/Polygon/commit/6d7645923c667f02fa516bd847dba30bded3a38b
